#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════
#  NasTech Guardian — One-Line Installer
#  curl -fsSL https://raw.githubusercontent.com/nastech-ai/NasGuardian/main/install.sh | bash
# ════════════════════════════════════════════════════════════════════

set -euo pipefail

REPO_URL="https://github.com/nastech-ai/NasGuardian"
RAW_URL="https://raw.githubusercontent.com/nastech-ai/NasGuardian/main"
INSTALL_DIR="$HOME/nastech-guardian"

R='\033[0;31m'; G='\033[0;32m'; Y='\033[1;33m'
B='\033[0;34m'; C='\033[0;36m'; N='\033[0m'; BOLD='\033[1m'

banner() {
  echo ""
  echo -e "${BOLD}${C}╔══════════════════════════════════════════════════════╗${N}"
  echo -e "${BOLD}${C}║  🛡️  NasTech Guardian — Installer                    ║${N}"
  echo -e "${BOLD}${C}║  Multi-agent CI/CD + Telegram Bot for Android/Termux ║${N}"
  echo -e "${BOLD}${C}╚══════════════════════════════════════════════════════╝${N}"
  echo ""
}

ok()  { echo -e "${G}[✓]${N} $*"; }
err() { echo -e "${R}[✗]${N} $*"; }
inf() { echo -e "${B}[→]${N} $*"; }
wrn() { echo -e "${Y}[!]${N} $*"; }
ask() { echo -e "${Y}[?]${N} $*"; }

# ── Detect environment ────────────────────────────────────────────────
detect_env() {
  if [ -d "/data/data/com.termux" ] || [ -n "${TERMUX_VERSION:-}" ]; then
    ENV="termux"
  elif [ "$(uname)" = "Darwin" ]; then
    ENV="macos"
  else
    ENV="linux"
  fi
  ok "Environment: $ENV"
}

# ── Install system packages ───────────────────────────────────────────
install_packages() {
  inf "Installing system packages…"
  case "$ENV" in
    termux)
      pkg update -y -q 2>/dev/null || true
      pkg install -y python git tmux curl openssh 2>/dev/null || true
      ;;
    linux)
      if command -v apt-get &>/dev/null; then
        sudo apt-get update -qq 2>/dev/null || true
        sudo apt-get install -y python3 python3-pip git curl 2>/dev/null || true
      elif command -v dnf &>/dev/null; then
        sudo dnf install -y python3 python3-pip git curl 2>/dev/null || true
      fi
      ;;
    macos)
      if command -v brew &>/dev/null; then
        brew install python3 git 2>/dev/null || true
      fi
      ;;
  esac
  ok "System packages ready"
}

# ── Clone or update repo ──────────────────────────────────────────────
clone_repo() {
  if [ -d "$INSTALL_DIR/.git" ]; then
    inf "Updating existing installation at $INSTALL_DIR…"
    git -C "$INSTALL_DIR" pull --ff-only origin main 2>/dev/null \
      || git -C "$INSTALL_DIR" pull --ff-only origin master 2>/dev/null \
      || true
    ok "Repository updated"
  else
    inf "Cloning NasGuardian to $INSTALL_DIR…"
    git clone --depth=1 "$REPO_URL" "$INSTALL_DIR"
    ok "Repository cloned"
  fi
}

# ── Install Python deps ───────────────────────────────────────────────
install_python_deps() {
  inf "Installing Python dependencies…"
  BOT_REQ="$INSTALL_DIR/scripts/telegram_bot/requirements.txt"
  if [ -f "$BOT_REQ" ]; then
    pip install -r "$BOT_REQ" --quiet 2>&1 | tail -2 || true
    ok "Python dependencies installed"
  else
    pip install "python-telegram-bot>=20.7" requests apscheduler pillow --quiet || true
    ok "Core Python dependencies installed"
  fi
}

# ── Collect API keys ──────────────────────────────────────────────────
ENV_FILE="$HOME/.nastech_env"

load_existing_env() {
  [ -f "$ENV_FILE" ] && source "$ENV_FILE" 2>/dev/null || true
}

save_env() {
  {
    echo "# NasTech Guardian — API Keys"
    echo "# Generated by installer — $(date)"
    echo ""
    [ -n "${TELEGRAM_BOT_TOKEN:-}" ]  && echo "export TELEGRAM_BOT_TOKEN=\"$TELEGRAM_BOT_TOKEN\""
    [ -n "${TELEGRAM_CHAT_ID:-}" ]    && echo "export TELEGRAM_CHAT_ID=\"$TELEGRAM_CHAT_ID\""
    [ -n "${GROQ_API_KEY:-}" ]        && echo "export GROQ_API_KEY=\"$GROQ_API_KEY\""
    [ -n "${GEMINI_API_KEY:-}" ]      && echo "export GEMINI_API_KEY=\"$GEMINI_API_KEY\""
    [ -n "${OPENROUTER_API_KEY:-}" ]  && echo "export OPENROUTER_API_KEY=\"$OPENROUTER_API_KEY\""
    [ -n "${GITHUB_TOKEN:-}" ]        && echo "export GITHUB_TOKEN=\"$GITHUB_TOKEN\""
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
}

prompt_keys() {
  echo ""
  echo -e "${BOLD}🔑 API Key Setup${N}"
  echo -e "   Keys are saved to ${C}$ENV_FILE${N}"
  echo -e "   Press Enter to keep existing value. Get keys from:"
  echo -e "   • Telegram: @BotFather (create bot)"
  echo -e "   • Groq:     https://console.groq.com"
  echo -e "   • Gemini:   https://aistudio.google.com/apikey"
  echo -e "   • OpenRouter: https://openrouter.ai/keys"
  echo ""

  prompt_masked() {
    local var="$1" label="$2" current="${!1:-}"
    if [ -n "$current" ]; then
      local masked="${current:0:6}…${current: -3}"
      ask "$label [current: ${G}${masked}${N}]: "
    else
      ask "$label: "
    fi
    read -r val
    [ -n "$val" ] && eval "$var='$val'"
  }

  prompt_masked TELEGRAM_BOT_TOKEN "Telegram Bot Token (from @BotFather)"
  prompt_masked TELEGRAM_CHAT_ID   "Telegram Chat ID (your user/group ID)"
  prompt_masked GROQ_API_KEY       "Groq API Key (gsk_...)"
  prompt_masked GEMINI_API_KEY     "Gemini API Key (AIza...)"
  prompt_masked OPENROUTER_API_KEY "OpenRouter API Key (sk-or-...)"
  prompt_masked GITHUB_TOKEN       "GitHub Personal Access Token (ghp_...) [optional]"

  save_env
  ok "API keys saved to $ENV_FILE"
}

# ── Source env into shell ─────────────────────────────────────────────
add_to_shell() {
  local rc_file="$HOME/.bashrc"
  [ "$ENV" = "termux" ] && rc_file="$HOME/.bashrc"
  [ "$ENV" = "macos" ]  && rc_file="$HOME/.zshrc"

  local source_line="[ -f \"$ENV_FILE\" ] && source \"$ENV_FILE\""
  if ! grep -qF "$ENV_FILE" "$rc_file" 2>/dev/null; then
    echo "" >> "$rc_file"
    echo "# NasTech Guardian" >> "$rc_file"
    echo "$source_line" >> "$rc_file"
    ok "Added env sourcing to $rc_file"
  fi

  # Helpful aliases
  local aliases="
# NasTech Guardian aliases
alias nastech-start='bash $INSTALL_DIR/scripts/telegram_bot/run_bot.sh'
alias nastech-config='bash $INSTALL_DIR/scripts/nastech_config.sh'
alias nastech-update='git -C $INSTALL_DIR pull && bash $INSTALL_DIR/install.sh --no-prompt'
alias nastech-logs='cat /tmp/nastech_bot.log 2>/dev/null || echo \"Bot not running in tmux\"'
"
  if ! grep -q "nastech-start" "$rc_file" 2>/dev/null; then
    echo "$aliases" >> "$rc_file"
    ok "Added nastech-* aliases to $rc_file"
  fi
}

# ── Termux: auto-start on boot ────────────────────────────────────────
setup_termux_boot() {
  [ "$ENV" != "termux" ] && return
  local boot_dir="$HOME/.termux/boot"
  mkdir -p "$boot_dir"
  cat > "$boot_dir/nastech-guardian.sh" << BOOTEOF
#!/data/data/com.termux/files/usr/bin/bash
source "$ENV_FILE" 2>/dev/null || true
sleep 10
tmux new-session -d -s nastech-guardian \
  "cd $INSTALL_DIR && python3 scripts/telegram_bot/nastech_guardian_bot.py >> /tmp/nastech_bot.log 2>&1" 2>/dev/null || true
BOOTEOF
  chmod +x "$boot_dir/nastech-guardian.sh"
  ok "Termux:Boot auto-start configured"
}

# ── Start bot in tmux (Termux) or background (Linux) ─────────────────
start_bot() {
  source "$ENV_FILE" 2>/dev/null || true

  if [ -z "${TELEGRAM_BOT_TOKEN:-}" ]; then
    wrn "TELEGRAM_BOT_TOKEN not set — skipping bot start"
    wrn "Run: source $ENV_FILE && nastech-start"
    return
  fi

  if [ "$ENV" = "termux" ] && command -v tmux &>/dev/null; then
    # Kill existing session if any
    tmux kill-session -t nastech-guardian 2>/dev/null || true
    sleep 1
    tmux new-session -d -s nastech-guardian \
      "cd $INSTALL_DIR && source $ENV_FILE && \
       python3 scripts/telegram_bot/nastech_guardian_bot.py 2>&1 | tee /tmp/nastech_bot.log"
    ok "Bot started in tmux session 'nastech-guardian'"
    inf "View logs:  tmux attach -t nastech-guardian"
    inf "Detach:     Ctrl+B then D"
  else
    inf "Starting bot in background…"
    source "$ENV_FILE" 2>/dev/null || true
    nohup python3 "$INSTALL_DIR/scripts/telegram_bot/nastech_guardian_bot.py" \
      >> /tmp/nastech_bot.log 2>&1 &
    local pid=$!
    sleep 2
    if kill -0 "$pid" 2>/dev/null; then
      ok "Bot started (PID $pid)"
      inf "Logs: tail -f /tmp/nastech_bot.log"
    else
      err "Bot failed to start — check: cat /tmp/nastech_bot.log"
    fi
  fi
}

# ── Final summary ─────────────────────────────────────────────────────
show_summary() {
  echo ""
  echo -e "${BOLD}${G}╔══════════════════════════════════════════════════════╗${N}"
  echo -e "${BOLD}${G}║  ✅  NasTech Guardian installed successfully!         ║${N}"
  echo -e "${BOLD}${G}╚══════════════════════════════════════════════════════╝${N}"
  echo ""
  echo -e "  📁 Installed to: ${BOLD}$INSTALL_DIR${N}"
  echo -e "  🤖 Bot:          ${BOLD}@Nightscafebot${N}"
  echo ""
  echo -e "${BOLD}Useful commands:${N}"
  echo -e "  ${C}nastech-start${N}    — start the bot"
  echo -e "  ${C}nastech-config${N}   — manage API keys"
  echo -e "  ${C}nastech-update${N}   — update to latest version"
  echo -e "  ${C}nastech-logs${N}     — view bot logs"
  echo ""
  echo -e "${BOLD}Telegram commands:${N}"
  echo -e "  ${C}/start${N}           — welcome"
  echo -e "  ${C}/ask <question>${N}  — AI chat"
  echo -e "  ${C}/apikeys${N}         — view API keys"
  echo -e "  ${C}/setkey KEY val${N}  — change a key live"
  echo -e "  ${C}/status${N}          — CI/CD pipeline status"
  echo ""
  echo -e "  🔗 ${BOLD}https://github.com/nastech-ai/NasGuardian${N}"
  echo ""
}

# ── Main ──────────────────────────────────────────────────────────────
main() {
  banner
  detect_env
  install_packages
  clone_repo
  install_python_deps

  # --no-prompt flag skips key prompts (for update mode)
  if [[ "${1:-}" != "--no-prompt" ]]; then
    load_existing_env
    prompt_keys
  fi

  add_to_shell
  setup_termux_boot
  start_bot
  show_summary
}

main "$@"
